### ISSUE TITLE
InvalidArgumentError: Default AvgPoolingOp only supports NHWC on device type CPU

### ISSUE THREAD

**Issue by jgcaffari1** [vlawhern/arl-eegmodels#14]
When I try to fit the eegnet model, I get the following error:

InvalidArgumentError: Default AvgPoolingOp only supports NHWC on device type CPU
	 [[{{node average_pooling2d/AvgPool}} = AvgPool[T=DT_FLOAT, _class=["loc:@training/Adam/gradients/average_pooling2d/AvgPool_grad/AvgPoolGrad"], data_format="NCHW", ksize=[1, 1, 1, 4], padding="VALID", strides=[1, 1, 1, 4], _device="/job:localhost/replica:0/task:0/device:CPU:0"](activation/Elu)]]

I have cuda installed, but it does not appear to be working.  What is the appropriate cuda setup for gpu support?

**Comment by vlawhern** [comment]
Yeah that error comes up if you have tensorflow-cpu installed (or I'm guessing a broken tensorflow-gpu install). 

Assuming you have a valid CUDA install, you should just be able to use pip to install tensorflow-gpu; i.e.:

pip install tensorflow-gpu==1.X or
pip install tensorflow-gpu==2.0.0

since this code works with Tensorflow 2 as well. Note that I do all my work in Linux; I might not be able to help much if you're using Windows and CUDA..

**Comment by jgcaffari1** [comment]
This fixed my problem. Thank you!

**Comment by vlawhern** [comment]
Good to hear! Closing this but feel free to reopen if there are any other issues.
